version: '3.8'

services:
  app:
    build: .
    ports:
      - "3389:3389"
    environment:
      - NODE_ENV=production
      - USE_NODE=true
      - DATABASE_URL=mysql://root:123456@mysql:3306/daojusaas
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: daojusaas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: